// ***************************************************************************
//
// Delphi MVC Framework
//
// Copyright (c) 2010-2026 Daniele Teti and the DMVCFramework Team
//
// https://github.com/danieleteti/delphimvcframework
//
// ***************************************************************************
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ***************************************************************************


program DMVCFrameworkWebHookSample;

{$APPTYPE CONSOLE}

uses
  System.SysUtils,
  Web.ReqMulti,
  Web.WebReq,
  Web.WebBroker,
  MVCFramework,
  MVCFramework.Logger,
  MVCFramework.DotEnv,
  MVCFramework.Commons,
  MVCFramework.Serializer.Commons,
  IdContext,
  IdHTTPWebBrokerBridge,
  TaurusTLS,
  MVCFramework.Signal,
  ControllerU in 'ControllerU.pas',
  WebModuleU in 'WebModuleU.pas' {MyWebModule: TWebModule};

{$R *.res}

type
  TTLSHandler = class
    procedure OnGetSSLPassword(aSender: TObject; var aPassword: String; const aIsWrite: Boolean; var aOk: Boolean);
    procedure OnQuerySSLPort(aPort: Word; var vUseSSL: boolean);
    procedure ConfigureTLS(aServer: TIdHTTPWebBrokerBridge);
  end;

{ TTLSHandler }

procedure TTLSHandler.ConfigureTLS(aServer: TIdHTTPWebBrokerBridge);
var
  lTaurusTLSHandler: TTaurusTLSServerIOHandler;
begin
  lTaurusTLSHandler := TTaurusTLSServerIOHandler.Create(aServer);
  lTaurusTLSHandler.SSLOptions.Mode := sslmServer;
  lTaurusTLSHandler.DefaultCert.PublicKey := dotEnv.Env('https.cert.cacert', 'certificates\localhost.crt');
  lTaurusTLSHandler.DefaultCert.PrivateKey := dotEnv.Env('https.cert.privkey', 'certificates\localhost.key');
  lTaurusTLSHandler.OnGetPassword := OnGetSSLPassword;
  lTaurusTLSHandler.OnGetPassword := OnGetSSLPassword;
  aServer.IOHandler := lTaurusTLSHandler;
  aServer.OnQuerySSLPort := OnQuerySSLPort;
end;

procedure TTLSHandler.OnGetSSLPassword(aSender: TObject; var aPassword: String; const aIsWrite: Boolean; var aOk: Boolean);
begin
  aPassword := dotEnv.Env('https.cert.password', '');
  aOk := True;
end;

procedure TTLSHandler.OnQuerySSLPort(aPort: Word; var vUseSSL: boolean);
begin
  vUseSSL := true;
end;

procedure RunServer(aPort: Integer);
var
  LServer: TIdHTTPWebBrokerBridge;
  LSSLHandler: TTLSHandler;
  LProtocol: String;
begin
  LProtocol := 'http';
  LServer := TIdHTTPWebBrokerBridge.Create(nil);
  try
    LServer.OnParseAuthentication := TMVCParseAuthentication.OnParseAuthentication;
    LServer.DefaultPort := APort;
    LServer.KeepAlive := dotEnv.Env('dmvc.indy.keep_alive', True);
    LServer.MaxConnections := dotEnv.Env('dmvc.webbroker.max_connections', 0);
    LServer.ListenQueue := dotEnv.Env('dmvc.indy.listen_queue', 500);
    LSSLHandler := TTLSHandler.Create;
    try
      if dotEnv.Env('https.enabled', false) then //enable if you want HTTPS support
      begin
        LogI('HTTPS is enabled');
        LSSLHandler.ConfigureTLS(LServer);
        LProtocol := 'https';
      end
      else
      begin
        LogW('HTTPS is available but CURRENTLY NOT ENABLED');
      end;
    LServer.Active := True;
    LogI('Listening on ' + LProtocol + '://localhost:' + APort.ToString);
    LogI('Application started. Press Ctrl+C to shut down.');
    WaitForTerminationSignal;
    EnterInShutdownState;
    LServer.Active := False;
    finally
      LSSLHandler.Free;
    end;
  finally
    LServer.Free;
  end;
end;

begin
  { Enable ReportMemoryLeaksOnShutdown during debug }
  // ReportMemoryLeaksOnShutdown := True;
  IsMultiThread := True;

  // DMVCFramework Specific Configurations
  //   When MVCSerializeNulls = True empty nullables and nil are serialized as json null.
  //   When MVCSerializeNulls = False empty nullables and nil are not serialized at all.
  MVCSerializeNulls := True;

  // MVCNameCaseDefault defines the name case of property names generated by the serializers.
  //   Possibile values are: ncAsIs, ncUpperCase, ncLowerCase (default), ncCamelCase, ncPascalCase, ncSnakeCase
  MVCNameCaseDefault := TMVCNameCase.ncCamelCase;

  // UseConsoleLogger defines if logs must be emitted to also the console (if available).
  UseConsoleLogger := True;

  // UseLoggerVerbosityLevel defines the lowest level of logs that will be produced.
  UseLoggerVerbosityLevel := TLogLevel.levNormal;


  LogI('** DMVCFramework Server ** build ' + DMVCFRAMEWORK_VERSION);

  try
    if WebRequestHandler <> nil then
      WebRequestHandler.WebModuleClass := WebModuleClass;

    WebRequestHandlerProc.MaxConnections := dotEnv.Env('dmvc.handler.max_connections', 1024);

{$IF CompilerVersion >= 34} //SYDNEY+
    if dotEnv.Env('dmvc.profiler.enabled', False) then
    begin
      Profiler.ProfileLogger := Log;
      Profiler.WarningThreshold := dotEnv.Env('dmvc.profiler.warning_threshold', 1000);
      Profiler.LogsOnlyIfOverThreshold := dotEnv.Env('dmvc.profiler.logs_only_over_threshold', True);
    end;
{$ENDIF}

    RunServer(dotEnv.Env('dmvc.server.port', 443));
  except
    on E: Exception do
      LogF(E.ClassName + ': ' + E.Message);
  end;
end.
